### ISSUE TITLE
emuiigen.jar does not work on Java 8

### ISSUE THREAD

**Issue by MAN-biker** [XorTroll/emuiibo#264]
console:
`Error: Could not find or load main class emuiigen.jar`
win:
`A Java Exception has occurred.`

**Comment by XorTroll** [comment]
Run `java -jar emuiigen.jar`

**Comment by MAN-biker** [comment]
`
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xortroll/emuiibo/emuiigen/MainKt has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
`

`
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)
`

**Comment by XorTroll** [comment]
Yeah that's compatibility issues with java 8

**Comment by MAN-biker** [comment]
> Yeah that's compatibility issues with java 8

So, what exactly java version we need to work?
And can you fix this compatibility problem?
Thanks anyway.

**Comment by XorTroll** [comment]
Can you try this build? [emuiigen.zip](https://github.com/XorTroll/emuiibo/files/12396760/emuiigen.zip)

**Comment by MAN-biker** [comment]
> Can you try this build? [emuiigen.zip](https://github.com/XorTroll/emuiibo/files/12396760/emuiigen.zip)

`
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: B:\ (Системе не удается найти указанный путь)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.getOrCreate(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2445)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2414)
        at com.xortroll.emuiibo.emuiigen.ui.MainApplication.start(MainApplication.kt:43)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        ... 1 more
`

**Comment by XorTroll** [comment]
These appear to be issues with JavaFX and Java 8
I'll try to see if I can get this fixed since I'd really like to maintain Java 8 compatibility and Java 9+ as well without breaking any of them

**Comment by Barrytoo** [comment]
> Run `java -jar emuiigen.jar`

Having the same error. 
Pardon the question, but where should this be done?


> Can you try this build? [emuiigen.zip](https://github.com/XorTroll/emuiibo/files/12396760/emuiigen.zip)

This one doesn't throw an error nor runs at all, nothing happens in the foreground.

**Comment by magicparty** [comment]
my java version is java version "1.8.0_381"

got the error when I run the emuiigen

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xortroll/emuiibo/emuiigen/MainKt has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by impeeza** [comment]
use the latest version from discord
https://discord.com/channels/472179996857860096/771036774448496661/1145061539511029794

or use java DK 20

**Comment by XorTroll** [comment]
Last release fixes this

**Comment by MASSI-GAMING** [comment]
i can't open emuiigen.jar
any fix ?
